#!/usr/bin/env node
// Tiny static site builder — no dependencies.
// Reads src/pages/*.html (fragments with a front-matter comment block),
// wraps them in src/partials/layout.html, writes plain static files to public/.
// Vercel then serves public/ as-is: no build step required at deploy time.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, cpSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const PAGES_DIR = join(ROOT, "src/pages");
const LAYOUT_PATH = join(ROOT, "src/partials/layout.html");
const STATIC_DIR = join(ROOT, "static");
const OUT_DIR = join(ROOT, "public");

const NAV = [
  { slug: "home", href: "/", label: "Home", n: "" },
  { slug: "safety", href: "/safety/", label: "Safety", n: "01", safety: true },
  { slug: "fundamentals", href: "/fundamentals/", label: "Fundamentals", n: "02" },
  { slug: "positional-shooting", href: "/positional-shooting/", label: "Positional Shooting", n: "03" },
  { slug: "reading-conditions", href: "/reading-conditions/", label: "Reading Conditions", n: "04" },
  { slug: "gear-basics", href: "/gear-basics/", label: "Gear Basics", n: "05" },
  { slug: "kestrel-5700", href: "/kestrel-5700/", label: "Kestrel 5700 Elite", n: "06" },
  { slug: "ab-quantum", href: "/ab-quantum/", label: "AB Quantum App", n: "07" },
  { slug: "bags-bipods", href: "/bags-bipods/", label: "Bags & Bipods", n: "08" },
  { slug: "mildot-master", href: "/mildot-master/", label: "Mildot Master", n: "09" },
];

function buildNav(activeSlug) {
  const items = NAV.map((item) => {
    const active = item.slug === activeSlug ? " active" : "";
    const wrapClass = item.safety ? ' class="nav-safety"' : "";
    const numSpan = item.n ? `<span class="n">${item.n}</span>` : "";
    return `    <li${wrapClass}><a href="${item.href}" class="${active.trim()}">${numSpan}${item.label}</a></li>`;
  });
  return `  <ul>\n${items.join("\n")}\n  </ul>`;
}

function parseFrontMatter(raw) {
  const match = raw.match(/^<!--\s*([\s\S]*?)\s*-->\s*/);
  if (!match) {
    throw new Error("Missing front-matter comment block at top of page file");
  }
  const meta = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();
    meta[key] = value;
  }
  const content = raw.slice(match[0].length);
  return { meta, content };
}

function outPathFor(slug) {
  if (slug === "home") return join(OUT_DIR, "index.html");
  if (slug === "404") return join(OUT_DIR, "404.html");
  return join(OUT_DIR, slug, "index.html");
}

// Static assets that live directly in public/ (not generated from src/pages)
// and must be precached alongside the generated pages for offline use.
const STATIC_PRECACHE = [
  "/css/site.css",
  "/js/app.js",
  "/manifest.json",
  "/icons/icon.svg",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/print/wind-reading-field-card.html",
];

function buildServiceWorker(routeUrls) {
  const precache = ["/", "/offline/", ...routeUrls.filter((u) => u !== "/"), ...STATIC_PRECACHE];
  const unique = [...new Set(precache)];
  const cacheVersion = `sf-${Date.now()}`;

  const sw = `// Auto-generated by scripts/build.mjs — do not edit by hand.
const CACHE_NAME = ${JSON.stringify(cacheVersion)};
const OFFLINE_URL = "/offline/";
const PRECACHE_URLS = ${JSON.stringify(unique, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() =>
          caches.match(request).then((cached) => cached || caches.match(OFFLINE_URL))
        )
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => cached);
    })
  );
});
`;

  writeFileSync(join(OUT_DIR, "service-worker.js"), sw);
  console.log(`built  service-worker.js${" ".repeat(21)} -> public/service-worker.js  (${unique.length} precached URLs, cache ${cacheVersion})`);
}

function build() {
  mkdirSync(OUT_DIR, { recursive: true });
  cpSync(STATIC_DIR, OUT_DIR, { recursive: true });
  console.log(`copied static/                     -> public/  (css, js, icons, manifest.json, print)`);

  const layout = readFileSync(LAYOUT_PATH, "utf8");
  const files = readdirSync(PAGES_DIR).filter((f) => f.endsWith(".html"));

  if (files.length === 0) {
    console.error("No page fragments found in src/pages/");
    process.exit(1);
  }

  const routeUrls = [];

  for (const file of files) {
    const raw = readFileSync(join(PAGES_DIR, file), "utf8");
    const { meta, content } = parseFrontMatter(raw);
    if (!meta.title || !meta.nav) {
      throw new Error(`${file}: front-matter must include at least "title" and "nav"`);
    }
    const nav = buildNav(meta.nav);
    const html = layout
      .replaceAll("{{TITLE}}", meta.title)
      .replaceAll("{{DESCRIPTION}}", meta.description || "")
      .replaceAll("{{NAV}}", nav)
      .replace("{{CONTENT}}", () => content.trim());

    const finalOutPath = file === "404.html" ? join(OUT_DIR, "404.html") : outPathFor(meta.nav);
    mkdirSync(dirname(finalOutPath), { recursive: true });
    writeFileSync(finalOutPath, html);
    console.log(`built  ${file.padEnd(28)} -> ${finalOutPath.replace(ROOT + "/", "")}`);

    // 404.html and the offline fallback aren't part of the crawlable/precache route set:
    // 404 has no canonical URL, and offline.html IS the fallback target (precached separately below).
    if (file !== "404.html" && meta.nav !== "offline") {
      const url = meta.nav === "home" ? "/" : `/${meta.nav}/`;
      routeUrls.push(url);
    }
  }

  buildServiceWorker(routeUrls);
  console.log(`\n${files.length} pages built into public/`);
}

build();
